name: Gradle Package

on:
  release:
    types: [created]  # 当创建 release 时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # Step 3: Cache Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Step 5: Ensure gradlew is executable (add chmod)
      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      # Step 6: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 7: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts  
          path: ./build/libs/    

      # Step 8: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
